name: Backport on pull_request_target[closed]
on:
  pull_request_target:
    types: [closed]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
  issues: write # so it can create/update the dashboard issue
jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.merged
      && github.event.pull_request.head.repo.full_name != 'korthout/backport-action-test'
    steps:
      - uses: actions/checkout@v6
      - name: Backport
        id: backport
        uses: korthout/backport-action@korthout-move-to-esbuild
        with:
          # copy all labels (backport labels are automatically skipped)
          copy_labels_pattern: .+
          experimental: >
            {
              "detect_merge_method": true,
              "dashboard_enabled": true
            }
      - name: Print was_successful output
        run: echo "${{ steps.backport.outputs.was_successful }}"
      - name: Print was_successful_by_target output
        run: echo "${{ steps.backport.outputs.was_successful_by_target }}"
